### ISSUE TITLE
Problem with existing coordinates.

### ISSUE THREAD

**Issue by nkint** [vijithassar/d3-textwrap#12]
Hi, I have some text with fixed coordinates to wrap.
There is a problem in the padding computing: a string is added to a number:

in your code in `src/textwrap.js` at line 165

```
if (typeof padding === 'number') {
        text
            .attr('y', text.attr('y') + padding)
            .attr('x', text.attr('x') + padding);
    }
```

but `text.attr('x')` is already set and it is returning a string in my case.
So that in the end instead having a `<text>` with `x = 5` I have `x = 60`

For instance:

```
nodes.append('text').attr('x', 6)
 // ...
const _wrap = textwrap()
    .bounds({height: 4800, width: textWidth})
    .padding(1)
    .method('tspans')
  selectAll('text').call(_wrap)
```

This will fix it:

```
        if (typeof padding === 'number') {
            var cx = parseInt(text.attr('x')) || 0
            var cy = parseInt(text.attr('y')) || 0
            text
                .attr('y', cy + padding)
                .attr('x', cx + padding);
        }

```

Just prepearing a pull request.

**Comment by nkint** [comment]
I tried to write a test using the current test suite but `jsdom` is not implementing the svg things:

```
tape('padding on tspan works with text that already has coordinates', function(test) {
    var wrapper,
        padding;
    wrapper = textwrap();
    padding = 10;

    html = '<html><div></div></html>';
    jsdom.env(html, function(error, window) {
        var selection;
        document = global.document = window.document = jsdom(html);
        selection = d3.select('div')
            .append('svg')
            .append('text')
            .attr('x', 6)
        wrapper = textwrap()
            .bounds({height: 100, width: 100})
            .padding(1)
        d3.select('text').call(wrapper)
        var finalX = d3.select('text').attr('x')
        test.ok(finalX === 5);
        test.end();
    });
});
```

Gave me this error:
```
line_width = tspan.node().getComputedTextLength() || 0;
                                      ^

TypeError: tspan.node(...).getComputedTextLength is not a function
    at wrap.tspans (/Users/user/Code/ext/d3-textwrap/build/d3-textwrap.js:152:39)
    at Selection.selection_call [as call] (/Users/user/Code/ext/d3-textwrap/node_modules/d3-selection/build/d3-selection.js:500:14)
    at HTMLUnknownElement.<anonymous> (/Users/user/Code/ext/d3-textwrap/build/d3-textwrap.js:185:42)
    at Selection.selection_each [as each] (/Users/user/Code/ext/d3-textwrap/node_modules/d3-selection/build/d3-selection.js:536:39)
    at wrapper (/Users/user/Code/ext/d3-textwrap/build/d3-textwrap.js:184:21)
    at Selection.selection_call [as call] (/Users/user/Code/ext/d3-textwrap/node_modules/d3-selection/build/d3-selection.js:500:14)
    at Object.done (/Users/user/Code/ext/d3-textwrap/test/textwrap-test.js:109:27)
    at process.nextTick (/Users/user/Code/ext/d3-textwrap/node_modules/jsdom/lib/jsdom.js:320:18)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by vijithassar** [comment]
What is the string @nkint? According to the [SVG specification](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/x), the `x` attribute can be either a number or a percentage. The latter is parsed as a string by `d3.select` but it's not really a supported use case for this plugin, which only computes numbers, and casting to a number there would be unexpected behavior.

**Comment by vijithassar** [comment]
Thanks for the bug report! I've implemented a [similar fix](https://github.com/vijithassar/d3-textwrap/pull/23/commits/13be93c19b29aa64850f164e5d408d18d2729449) which preserves fractional values instead of parsing to an integer.
